apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpservice
  labels:
    app: phpservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpservice
  template:
    metadata:
      labels:
        app: phpservice
    spec:   # âœ… must be indented under template
      containers:
      - name: phpservice
        image: sudhirvashist99/phpapp:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: mysql-config
          - secretRef:
              name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: phpservice
spec:
  type: NodePort
  selector:
    app: phpservice
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30800
